#!/usr/bin/env bash

job_name=$1
max_wait_time=$2
wait_interval=$3
repository=$4
start_time=$(date +%s)
current_time=$start_time

while [ $((current_time - start_time)) -lt $max_wait_time ]; do
    jobs=$(gh run list -R "martijnarts/$repository")
    if [ "$(echo "${jobs}" | grep "${job_name}")" ]; then
        exit 0
    fi
    sleep $wait_interval
    current_time=$(date +%s)
done
exit 1
